version: "2"
services:
  php_nginx:
    image: registry.cn-shenzhen.aliyuncs.com/luler/hello_word_segment
    restart: always
    privileged: true
    ports:
      - 7744:7744
    volumes:
      - ./config/php/php.ini:/etc/php.ini
      - ./config/php/php.d:/etc/php.d
      - ./config/init.sh:/init.sh
      - ./code:/home/code
      - ./config/supervisor/supervisord.conf:/etc/supervisord.conf
      - ./config/supervisor/supervisord.d:/etc/supervisord.d
